
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 07 11:39:59 CET 2018
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 42;
  public static final int Y = 36;
  public static final int TIPOS = 30;
  public static final int DE = 3;
  public static final int DEVOLVER = 6;
  public static final int SUBPROGRAMAS = 29;
  public static final int PROGRAMA = 8;
  public static final int ENTERO = 9;
  public static final int SI = 14;
  public static final int FUNCION = 16;
  public static final int CIERTO = 25;
  public static final int DOS_PUNTOS = 37;
  public static final int ENTONCES = 4;
  public static final int RANGO = 2;
  public static final int PAR_IZDO = 24;
  public static final int FIN = 10;
  public static final int COR_IZDO = 17;
  public static final int IDENTIFICADOR = 43;
  public static final int COMIENZO = 35;
  public static final int SINO = 20;
  public static final int CONSTANTES = 33;
  public static final int ESCRIBIR = 34;
  public static final int PROCEDIMIENTO = 11;
  public static final int SUMA = 31;
  public static final int PUNTO_COMA = 38;
  public static final int COMILLA_DOBLE = 7;
  public static final int EOF = 0;
  public static final int PRODUCTO = 28;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int PAR_DCHO = 27;
  public static final int COMENTARIO = 45;
  public static final int MENOR = 39;
  public static final int COR_DCHO = 18;
  public static final int VECTOR = 15;
  public static final int ASIGNACION = 40;
  public static final int EN = 26;
  public static final int NO = 5;
  public static final int PUNTO = 41;
  public static final int VARIABLES = 21;
  public static final int FINAL = 46;
  public static final int FALSO = 22;
  public static final int BOOLEANO = 13;
  public static final int STRING = 44;
  public static final int PARA = 12;
  public static final int VAR = 23;
  public static final int EQUIVALENTE = 19;
}

