
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 11 14:22:03 CET 2018
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 45;
  public static final int Y = 40;
  public static final int TIPOS = 22;
  public static final int DE = 6;
  public static final int DEVOLVER = 8;
  public static final int SUBPROGRAMAS = 21;
  public static final int PROGRAMA = 17;
  public static final int ENTERO = 9;
  public static final int SI = 19;
  public static final int FUNCION = 14;
  public static final int CIERTO = 3;
  public static final int DOS_PUNTOS = 34;
  public static final int ENTONCES = 10;
  public static final int RANGO = 35;
  public static final int PAR_IZDO = 27;
  public static final int FIN = 13;
  public static final int COR_IZDO = 29;
  public static final int IDENTIFICADOR = 44;
  public static final int COMIENZO = 4;
  public static final int SINO = 20;
  public static final int CONSTANTES = 5;
  public static final int ESCRIBIR = 11;
  public static final int PROCEDIMIENTO = 16;
  public static final int SUMA = 36;
  public static final int PUNTO_COMA = 33;
  public static final int COMILLA_DOBLE = 26;
  public static final int EOF = 0;
  public static final int PRODUCTO = 37;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int PAR_DCHO = 28;
  public static final int COMENTARIO = 31;
  public static final int MENOR = 38;
  public static final int COR_DCHO = 30;
  public static final int VECTOR = 25;
  public static final int ASIGNACION = 42;
  public static final int EN = 7;
  public static final int NO = 41;
  public static final int VARIABLES = 24;
  public static final int PUNTO = 18;
  public static final int FALSO = 12;
  public static final int ERRORID1 = 43;
  public static final int BOOLEANO = 2;
  public static final int STRING = 46;
  public static final int PARA = 15;
  public static final int VAR = 23;
  public static final int EQUIVALENTE = 39;
}

